input_dir: dataset
output_dir: dataset/protein_embeddings
glob_patterns: ["*.dat"]
model: facebook/esm2_t36_3B_UR50D
num_data_workers: 1
batch_size: 4
data_reader_fn: single_sequence_per_line
embedding_model_fn: esm
compute_settings:
  name: workstation
  available_accelerators: ["0", "1"]
