input_dir: dataset
output_dir: dataset/smineg_embeddings
glob_patterns:
- '*neg.smi'
model: ibm/MoLFormer-XL-both-10pct
num_data_workers: 1
batch_size: 64
data_reader_fn: single_sequence_per_line
embedding_model_fn: auto
compute_settings:
    name: workstation
    available_accelerators:
    - '0'
    - '1'
    worker_port_range:
    - 10000
    - 20000
    retries: 1
    label: htex
