input_dir: dataset
output_dir: dataset/smineg_embeddings
glob_patterns: ["*neg.smi"]
#model: ibm/MoLFormer-XL-both-10pct
num_data_workers: 2
batch_size: 64
data_reader_fn: single_sequence_per_line
embedder_config:
    name: auto
    pretrained_model_name_or_path: ibm/MoLFormer-XL-both-10pct
    compile_model: false
#embedding_model_fn: auto
compute_config:
  name: workstation
  available_accelerators: ["2", "3"]
