input_dir: dataset
output_dir: dataset/smi_embeddings_test
glob_patterns: ["*.smi"]
#model: ibm/MoLFormer-XL-both-10pct
num_data_workers: 1
batch_size: 64
data_reader_fn: single_sequence_per_line
embedder_config:
    name: auto
    pretrained_model_name_or_path: ibm/MoLFormer-XL-both-10pct
    compile_model: false
#embedding_model_fn: auto
compute_config:
  name: workstation
  available_accelerators: ["1", "2"]
